# Generated by Django 4.2.24 on 2025-09-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("surprise", "Surprise"),
                            ("disgust", "Disgust"),
                            ("neutral", "Neutral"),
                        ],
                        help_text="Detected emotion that triggered this session",
                        max_length=20,
                    ),
                ),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                (
                    "user_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="User's IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User's browser information"
                    ),
                ),
            ],
            options={
                "verbose_name": "Music Session",
                "verbose_name_plural": "Music Sessions",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("surprise", "Surprise"),
                            ("disgust", "Disgust"),
                            ("neutral", "Neutral"),
                        ],
                        help_text="Emotion for this playlist",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Playlist name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Playlist description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Playlist cover image (optional)",
                        null=True,
                        upload_to="playlist_covers/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this playlist is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emotion Playlist",
                "verbose_name_plural": "Emotion Playlists",
                "ordering": ["emotion"],
            },
        ),
        migrations.AlterModelOptions(
            name="emotionsong",
            options={
                "ordering": ["emotion", "order", "title"],
                "verbose_name": "Emotion Song",
                "verbose_name_plural": "Emotion Songs",
            },
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="album",
            field=models.CharField(
                blank=True, help_text="Album name (optional)", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Album cover image (optional)",
                null=True,
                upload_to="album_covers/",
            ),
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="Song duration (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this song is active in playlists"
            ),
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in playlist (0 = first)"
            ),
        ),
        migrations.AddField(
            model_name="emotionsong",
            name="play_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this song has been played"
            ),
        ),
        migrations.AlterField(
            model_name="emotionsong",
            name="artist",
            field=models.CharField(
                default="Unknown Artist", help_text="Artist name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="emotionsong",
            name="emotion",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                    ("fear", "Fear"),
                    ("surprise", "Surprise"),
                    ("disgust", "Disgust"),
                    ("neutral", "Neutral"),
                ],
                help_text="Select the emotion this song represents",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emotionsong",
            name="title",
            field=models.CharField(
                default="Untitled", help_text="Song title", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="SongPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_start", models.DateTimeField(auto_now_add=True)),
                (
                    "play_duration",
                    models.DurationField(
                        blank=True, help_text="How long the song was played", null=True
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the song was played to completion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.musicsession",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.emotionsong",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song Play",
                "verbose_name_plural": "Song Plays",
                "ordering": ["-play_start"],
            },
        ),
        migrations.AddField(
            model_name="musicsession",
            name="playlist",
            field=models.ForeignKey(
                help_text="Playlist played in this session",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.playlist",
            ),
        ),
        migrations.AddField(
            model_name="musicsession",
            name="songs_played",
            field=models.ManyToManyField(
                help_text="Songs played in this session",
                through="app.SongPlay",
                to="app.emotionsong",
            ),
        ),
    ]
