# Generated by Django 5.2.6 on 2025-09-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Fear', 'Fear'), ('Surprise', 'Surprise'), ('Disgust', 'Disgust'), ('Neutral', 'Neutral')], help_text='Select the emotion this song represents', max_length=20)),
                ('song_file', models.FileField(help_text='Upload an MP3 file for this emotion', upload_to='songs/')),
                ('title', models.CharField(blank=True, help_text='Song title (optional)', max_length=200)),
                ('artist', models.CharField(blank=True, help_text='Artist name (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emotion Song',
                'verbose_name_plural': 'Emotion Songs',
                'ordering': ['emotion', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Training image for emotion detection', upload_to='training_images/')),
                ('labeled_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], help_text='The emotion this image represents', max_length=20)),
                ('detected_emotion', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], help_text='The emotion detected by the system', max_length=20, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score of the detection')),
                ('is_correct', models.BooleanField(default=True, help_text='Whether the detection was correct')),
                ('wrong_attempts', models.IntegerField(default=0, help_text='Number of times this image was detected incorrectly')),
                ('needs_review', models.BooleanField(default=False, help_text='Whether this image needs admin review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted this image', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to='app.trainingimage')),
            ],
            options={
                'verbose_name': 'Emotion Detection Log',
                'verbose_name_plural': 'Emotion Detection Logs',
                'ordering': ['-detection_timestamp'],
            },
        ),
    ]
